### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by AdrianWennberg** [vmihailenco/tagparser#1]
HI!
The repository is currently missing a license, which means that we cannot use newer versions of [msgpack](https://github.com/vmihailenco/msgpack). 

Could you please add one? BSD would make sense as it is what you are using for [the msgpack license](https://github.com/vmihailenco/msgpack/blob/5a9835413072439b26e1d1227188a9489c6bb002/LICENSE).

**Comment by AdrianWennberg** [comment]
@vmihailenco would you mind having a look at this when you have the time?

**Comment by vmihailenco** [comment]
Sorry, somehow I've missed the first notification. Should be closed by https://github.com/vmihailenco/tagparser/commit/dca2180cb9545db13d849570f581ad3e01f5bc48

**Comment by AdrianWennberg** [comment]
Thank you!
